### ISSUE TITLE
User Story 10, Favorite Index Page

### ISSUE THREAD

**Issue by jrsewell400** [kristastadler/paired_adopt_dont_shop#32]
As a visitor
When I have added pets to my favorites list
And I visit my favorites index page ("/favorites")
I see all pets I've favorited
Each pet in my favorites shows the following information:
- pet's name (link to pets show page)
- pet's image

**Comment by kristastadler** [comment]
Pet name isn't a link.

**Comment by kristastadler** [comment]
I don't think your if / else statement is working -- when I open the Favorites Index on the server, it's just a list of all the pets in the shelter, whether they have been Favorited or not.
