### ISSUE TITLE
User Story 8, Favorite Indicator

### ISSUE THREAD

**Issue by jrsewell400** [kristastadler/paired_adopt_dont_shop#34]
As a visitor
I see a favorite indicator in my navigation bar
The favorite indicator shows a count of pets in my favorites list
I can see this favorite indicator from any page in the application

**Comment by kristastadler** [comment]
Created favorite indicator with placeholder for count of pets.

Still to-do:
- Create dynamic count of pets once we complete cookies / sessions lesson.
